# Generated by Django 4.2.4 on 2023-08-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeoffHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'timeoff_header',
            },
        ),
        migrations.CreateModel(
            name='TimeoffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('limit', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'timeoff_type',
            },
        ),
        migrations.CreateModel(
            name='TimeoffHeaderDateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('timeoff_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TimeoffHeaderDateMapping_timeoff_header', to='timeoff.timeoffheader')),
            ],
            options={
                'db_table': 'timeoffheader_date_mapping',
            },
        ),
        migrations.AddField(
            model_name='timeoffheader',
            name='time_off_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TimeoffHeader_timeoff_type', to='timeoff.timeofftype'),
        ),
    ]
