# Generated by Django 4.2.4 on 2023-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0002_timeoffheader_created_at_timeoffheader_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffheader',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
